export const ADD_CRICKETER = "ADD_CRICKETER";
export const FETCH_CRICKETERS = "FETCH_CRICKETERS";
export const DELETE_CRICKETER = "DELETE_CRICKETER";
export const UPDATE_CRICKETER = 'UPDATE_CRICKETER';